### ISSUE TITLE
Doesn't show up with Polybar

### ISSUE THREAD

**Issue by archerhush** [vyachkonovalov/polybar-gmail#10]
I'm trying to run this, but it doesn't work.

This is the exact code I'm using: https://github.com/vyachkonovalov/polybar-gmail#module

My whole polybar config I added that code to: https://github.com/electro7/dot_arch/blob/master/.config/polybar/config
Credentials are ok, and other, but it just doesn't show up with Polybar. I also don't understand how it should work, I'm trying to launch this on my terminal, `~/.config/polybar/gmail/launch.py` and I get this:

```
 ~
%{F#e06c75} %{F-}16266
 ~
```

in loop which should be used for updating gmail incoming mails. But I also tried to send myself a mail and it just keeps printing those strings, but not something different which should let me understand that I got new message.

**Comment by crabvk** [comment]
I just checked, the script seems to work just fine.
Did you add `gmail` to your `modules-right` config string?

`~` in output means the current value (inbox emails count) is not known and it's updating (at least trying to). The value can be not known for two reasons:
1.  the script is just launched
2.  an error happen (e.g. internet connection lost)
