### ISSUE TITLE
Permission error after pasting the verification code

### ISSUE THREAD

**Issue by tadec** [vyachkonovalov/polybar-gmail#11]
Traceback (most recent call last):
  File "/home/tadec/.config/polybar/gmail/auth.py", line 25, in <module>
    with open(CREDENTIALS_PATH, 'w') as creds_file:
PermissionError: [Errno 13] Permission denied: '/home/tadec/.config/polybar/gmail/credentials.json'

Hi, I have trouble going through with the google verification, this is the message I get after pasting the verif code into my terminal. I suppose it's something trivial, but I have no clue how to solve this.

Thanks!

**Comment by crabvk** [comment]
Is `/home/tadec` your home directory?
```shell
bash -c 'if [ $HOME = "/home/tadec" ]; then echo yes; else echo no; fi'
```
If 'yes', then try to change permissions for `~/.config/polybar/gmail`.

**Comment by tadec** [comment]
Thanks a lot and sorry for the dumb question issued, the permissions weren't set properly for that folder. 
Would you mind me asking, is there a way to make the script pull the number not from the whole inbox, but a specific label? As in primary, etc.

**Comment by crabvk** [comment]
No problem. Look at [example](https://github.com/vyachkonovalov/polybar-gmail#script-arguments) and "Get list of all your mailbox labels".
