### ISSUE TITLE
How to use last section?  

### ISSUE THREAD

**Issue by chrisco23** [vyachkonovalov/polybar-gmail#12]
Can you please explain how to use the stuff in the last section "Get list of all your mailbox labels"?

**Comment by crabvk** [comment]
You should run that code in python REPL (Python Interactive Shell). In terminal run `python` and copy-paste the code (but replace `CREDENTIALS_PATH` with actual path to `credentials.json`).

**Comment by chrisco23** [comment]
I see.  Thanks, and thanks for this module.
