### ISSUE TITLE
Failed to play sound: IO Error

### ISSUE THREAD

**Issue by ghost** [vyachkonovalov/polybar-gmail#15]
I'm on Arch Linux and am using i3wm-gaps. Everything works ok aside from the sounds. I get "Failed to play sound: IO Error" (appears where the module is in polybar) when I get an email.

**Comment by crabvk** [comment]
Can't reproduce on my system, but the error comes from `canberra-gtk-play -i message` (launch.py executes this command).
You may disable sound for polybar-gmail with `-ns` (or `--nosound`) argument.
