### ISSUE TITLE
Update time

### ISSUE THREAD

**Issue by shirobachi** [vyachkonovalov/polybar-gmail#17]
Hi, 

Is it possible to change the interval time of checking the mail? I think it's not working properly.. 
Basically sometimes whole day I've mail but not see any info from your module, now I just restart polybar and unfortunately, it did not catch my mails as well ;/ 

Thanks in advance!

**Comment by crabvk** [comment]
No, it's hardcoded [here](https://github.com/crabvk/polybar-gmail/blob/bf6b62835f1c7e95a17ba93a1615b6d1cf797fa5/launch.py#L50), I think 10 seconds is ok.  
Maybe your mail isn't in INBOX, you could try to [list all labels](https://github.com/crabvk/polybar-gmail#get-list-of-all-your-mailbox-labels) and run the script with `--label` argument. But then passing multiple labels to `launch.py` is not supported.

**Comment by shirobachi** [comment]
Yea 10 secs is very good, 

I changed tail -> true and it's working.. what tail is doing anyway? I was thinking that it will show module only if mail >0
I also added label :)


Thanks a lot

**Comment by crabvk** [comment]
Yup, `tail = true` is required, because the scripts is running constantly.

**Comment by shirobachi** [comment]
I understand, thank you! 

As I understand if not possible to module disappear if no new mails?

**Comment by crabvk** [comment]
No, but feel free to change the source for yourself, the code is simple.

**Comment by shirobachi** [comment]
Would you like if I would make PR adding optional feature?

**Comment by crabvk** [comment]
Sure
