### ISSUE TITLE
Color Issue

### ISSUE THREAD

**Issue by Ace-Krypton** [vyachkonovalov/polybar-gmail#19]
![Screenshot_2022-03-03_21-46-33](https://user-images.githubusercontent.com/75210504/156650398-b360ec2b-aa85-424a-8f45-94d8069207f1.png)
![Screenshot_2022-03-03_21-47-32](https://user-images.githubusercontent.com/75210504/156650409-cdf5cc50-792a-4070-a63e-97524e08b8fe.png)

Seems like color is not working, even changing it from polybar config is not working (Background color worked but not icon color).

**Comment by crabvk** [comment]
This color passed with `-c`/`--color` argument is used when you have messages in your Inbox.
I don't currently have xorg/polybar installed and can't test custom icon color (`format-foreground`).
