### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by SeraphyBR** [vyachkonovalov/polybar-gmail#2]
I found your module nice, but I have a lot of unread and old emails. I had to make a small edit in launch.py to show the emails that were not read, but more recent. I simply added "newer_than: 5d" to the value that the "list" variable will receive. If it could be interesting to change the time as an argument to the script.

My source: https://support.google.com/mail/answer/7190?hl=en

In my dotfile: https://github.com/SeraphyBR/DotFiles/blob/master/config/polybar/gmail/launch.py

**Comment by crabvk** [comment]
@SeraphyBR
We've changed the way unread messages get in (thanks to @iwconfig) https://git.io/vb2oE
can't use search operators with that.
Also, why don't you use 'Mark as read' for all the old messages? (just asking :relaxed:)

**Comment by SeraphyBR** [comment]
I even use the mark as read for the old messages, but I have certain 49,000 unread messages and the bookmark only selects the 50 messages displayed on the same page. I do not know a way to mark as read, all at once, 49 thousand.
I have a lot because of social networks, only in those years recently I have been disabling what I could of messages coming from these places. ~Google Translate

**Comment by crabvk** [comment]
That's how to mark all gmail inbox messages as read:
```bash
cd ~/.config/polybar/gmail
```
Save python script below to file `mark_read.py`
```python
import os
from apiclient import discovery
from oauth2client import file

DIR = os.path.dirname(os.path.realpath(__file__))
CREDENTIALS_PATH = os.path.join(DIR, 'credentials.json')

gmail = discovery.build('gmail', 'v1', credentials=file.Storage(CREDENTIALS_PATH).get())
messages = gmail.users().messages().list(userId='me', labelIds=['INBOX', 'UNREAD'], maxResults=42000).execute()
message_ids = list(map(lambda msg : msg['id'], messages['messages']))

chunk_size = 1000 # max limit per request is 1k
for i in range(0, len(message_ids), chunk_size):
    chunk = message_ids[i:i+chunk_size]
    gmail.users().messages().batchModify(userId='me', body={ 'ids': chunk, 'removeLabelIds': ['UNREAD'] }).execute()
```
Then change auth scope in auth.py
```diff
 import httplib2
 import webbrowser
 from oauth2client import client, file
 
-SCOPE = 'https://www.googleapis.com/auth/gmail.readonly'
+SCOPE = 'https://www.googleapis.com/auth/gmail.modify'
 REDIRECT_URI = 'urn:ietf:wg:oauth:2.0:oob'
 DIR = os.path.dirname(os.path.realpath(__file__))
 CLIENT_SECRETS_PATH = os.path.join(DIR, 'client_secrets.json')
```
Remove old and obtain new credentials
```bash
rm credentials.json
./auth.py
```
and finally run the script
```bash
python mark_read.py
```

**Comment by SeraphyBR** [comment]
Thanks for the script, it worked. I had other unread messages that were not marked because they were not in the inbox tab. But apart from that, it worked. I also found how to make the selection of all the messages corresponding to my search in gmail, and did a little cleaning on it. Thank you again.

**Comment by crabvk** [comment]
Your welcome :blush:
