### ISSUE TITLE
Not an issue, more of a question (Possibility of a Waybar Module) 

### ISSUE THREAD

**Issue by ghost** [vyachkonovalov/polybar-gmail#28]
I have switched from Polybar to Waybar since I moved to Hyprland and Wayland. I was wondering if you have any plans on making this available as a Waybar module too (like the protonmail one is). Would love to use it on Waybar as well. :)

I was trying to add the `enhancement` label to this, but couldn't figure out how to add it. LOL

**Comment by crabvk** [comment]
I plan to rewrite the code, make it as a package, and add waybar support. Will do that soon.

**Comment by crabvk** [comment]
New version is in the repo (kindly read the new README). One notible breaking change is you need to periodically call the script to get updates.
App is awaiting review from Google at the moment, that should take about two weeks.
