### ISSUE TITLE
Bar-gmail is notifying gmail spam mails

### ISSUE THREAD

**Issue by druidamix** [vyachkonovalov/polybar-gmail#35]
Hello,

I'm using your plugin. However, it notifies every new spam mail. Seems a bug.

Thanks.

**Comment by crabvk** [comment]
That's not a bug, but having a flag like `--no-spam` would be a good feature though.

**Comment by druidamix** [comment]
In my opinion, spam mails should be a secondary option, not by default. I receive more spam mails than normal ones. Moreover, they only appear as notifications.

**Comment by crabvk** [comment]
I agree.

**Comment by crabvk** [comment]
@druidamix
The issue should be fixed now, please check and let me know if it works (because I don't have any new spam messages at the moment).

**Comment by druidamix** [comment]
Seems to be working. No spam mails notifications.

Thank you!
