### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by nahuelcamillo** [vyachkonovalov/polybar-gmail#36]
Hello!

It's not a bug, just a suggestion. I'm using your plugin to display a counter of unread emails in my Polybar. I also use Dunst and would appreciate an option to enable or disable notifications in it. I attempted to modify the Dunst config file by adding 'bar-gmail' to suppress notifications, but I suspect I might not be using the correct 'appname' as it didn't work.

Thanks!

**Comment by crabvk** [comment]
Hello.
`bar-gmail` already has the `--no-notify` (`-dn` for short) argument to disable desktop notifications.
Also, you can get full list of available arguments with `bar-gmail --help`.

**Comment by nahuelcamillo** [comment]
Hi!

Yes, I tried with `-dn` and `--no-notify` but it didn't work for me.
Now, reading the code I obtained the appname and I solved this issue including it in my dunst config file.

**Comment by crabvk** [comment]
Oh, it's a bug then.

**Comment by crabvk** [comment]
I've checked the `--no-notify` argument and it works as expected.
And if you look at the code
https://github.com/crabvk/bar-gmail/blob/b989131d5d341e85009eac13c998f1ba67945767/bar_gmail/app.py#L106
there's condition on which notifications sending is run or not.
