### ISSUE TITLE
Actionable notifications

### ISSUE THREAD

**Issue by clinta** [vyachkonovalov/polybar-gmail#37]
A feature request:

It would be really nice if notifications could be clicked, and clicking them opened a browser to the specific message.

For my use case, since I use multiple emails with different browser profiles, I'd like to be able to customize the browser used, instead of just using the default browser.

**Comment by crabvk** [comment]
> It would be really nice if notifications could be clicked, and clicking them opened a browser to the specific message.

This requires bar-gmail script to be running and waiting for the response from notification (via dbus) while notification is shown. Which is not possible, because the cycle of the script is to check, show notifications and exit.

**Comment by clinta** [comment]
I think it should be possible to setup a dbus activated systemd unit that will listen for the action message and take the appropriate action.

This seems to be somewhat under-documented in systemd, so I'm trying to figure it out. But if it works, then bar-gmail should be able to create this service as a transient unit the first time it runs.

Would you be interested in a PR that used this approach.

**Comment by crabvk** [comment]
I don't like the systemd approach because it's not universal, for example I'm on a non-systemd distro (Artix).

**Comment by clinta** [comment]
Okay, how would you feel about a more fundamental change, that changes bar-gmail into a continuous script, that uses it's own interval to check for messages and provide the waybar updates. So that it can async listen for the notification actions?

**Comment by crabvk** [comment]
I personally don't need that. Clicking the icon that opens the inbox is just enough, IMHO. Keeping the script simple is also a priority. But feel free to fork.
