### ISSUE TITLE
Issue with multiple accounts

### ISSUE THREAD

**Issue by christopherbruce** [vyachkonovalov/polybar-gmail#38]
It looks like it's (maybe?) pulling the unread count from the `session.json` file, which is being written by both instances, so when I have 1 email in "home" is is also showing 1 email in "work"

![bar-gmail](https://github.com/crabvk/bar-gmail/assets/12052767/8513071c-868b-4dd3-89d3-cbc53489d710)

I have generated two credentials files and configured my polybar modules like this (edited to remove styling)
```
[module/gmail-home]
type = custom/script
interval = 60
exec = bar-gmail -f polybar -b "" -cr home/credentials.json
click-left = ~/.config/i3/scripts/open_gmail_home

[module/gmail-work]
type = custom/script
interval = 60
exec = bar-gmail -f polybar -b "" -cr work/credentials.json
click-left = ~/.config/i3/scripts/open_gmail_work
```

**Comment by crabvk** [comment]
Sorry for long reply.
This feature isn't implemented yet.

**Comment by crabvk** [comment]
I've added new `--cache-dir CACHE_DIR` argument in the latest release 1.0.6. Feel free to reopen the issue if something doesn't work for you.
