### ISSUE TITLE
Where to store credentials

### ISSUE THREAD

**Issue by pat-s** [vyachkonovalov/polybar-gmail#4]
After running `auth.py`, where should I store the credentials key?

**Comment by crabvk** [comment]
@pat-s 
After you run `auth.py` the google accounts url will be opened in your default browser
![screenshot](https://i.imgur.com/AyApWht.png)
Press ALLOW button, then copy given code back to the terminal (where you run `auth.py`) and press ENTER
File `credentials.json` will be created in current dir.

**Comment by pat-s** [comment]
Thanks. Some hints that maybe worth putting into the README: 

1. I had no Chromium installed and opening the xdg-link with Vivaldi does not seem to work properly.
2. The creation of `credentials.json` failed under `.config` due to permission errors. Maybe its safer to point to `~./polybar-scripts/gmail`.

Got it working now. Thanks :smile:
