### ISSUE TITLE
Authentication Issue

### ISSUE THREAD

**Issue by XxCoder99xX** [vyachkonovalov/polybar-gmail#42]
Running ```bar-gmail auth``` brings up the URL and I can click on it. However, when selecting my account, this error pops up:
![image](https://github.com/user-attachments/assets/7dbdbcda-80ae-4757-b70d-5b4ee64c7c45)

Upon further investigation, I found that to stop this, I needed to enable 'LSA(Less Secure Account)'. However, this function no longer exists (deprecated and erased), meaning I can no longer authenticate. Is there a workaround?

**Comment by crabvk** [comment]
There's nothing I can do about it. I've tried to publish the app according to the rules, but Google reviewers rejected my submission several times, so I gave up trying. Blame Google, not me.
You can register your own app in [Google Console](https://console.cloud.google.com) and use it in test mode, IIRC.

**Comment by XxCoder99xX** [comment]
Ah, I see. I was able to use a different Gmail bar extension that used IMAPLib and Python. Thank you for clarifying.
