### ISSUE TITLE
auth.py unable to refresh credentials if credentials.json exists but is empty

### ISSUE THREAD

**Issue by Dr-Dd** [vyachkonovalov/polybar-gmail#5]
For some unknown reason, my `credentials.json` file emptied itself. This results in `storage.get()` failing. To solve the problem i've added another condition to the if statement 
`if pathlib.Path(CREDENTIALS_PATH).is_file() and os.stat(CREDENTIALS_PATH).st_size != 0:` 
Don't know if that's an appropriate solution.

**Comment by crabvk** [comment]
I think the best solution in your case would be to delete credentials.json file.

**Comment by scrouthtv** [comment]
`Traceback (most recent call last):
  File "./auth.py", line 18, in <module>
    credentials.refresh(httplib2.Http())
  File "/usr/lib/python3.7/site-packages/oauth2client/client.py", line 545, in refresh
    self._refresh(http)
  File "/usr/lib/python3.7/site-packages/oauth2client/client.py", line 761, in _refresh
    self._do_refresh_request(http)
  File "/usr/lib/python3.7/site-packages/oauth2client/client.py", line 819, in _do_refresh_request
    raise HttpAccessTokenRefreshError(error_msg, status=resp.status)
oauth2client.client.HttpAccessTokenRefreshError: invalid_grant: Bad Request
`
Fixed it by removing the credentials.json but this is a weird error message
