### ISSUE TITLE
Limiting access to data in your Google Account

### ISSUE THREAD

**Issue by Chip000** [vyachkonovalov/polybar-gmail#6]
Hello,
I received the following message from google:

Although you don’t need to do anything, we wanted to let you know that the following apps may no longer be able to access some data in your Google Account, including your Gmail content. If these apps are unable to meet the deadline to comply with our updated data policy requirements, they'll lose access to your Account starting July 15th, 2019.
Polybar Gmail
We are making this change as part of ongoing efforts to make sure your data is protected and private.
You can always view, manage and remove apps you’ve given access to your account by visiting your Google Account. 

How should I proceed?

**Comment by crabvk** [comment]
Hello. Recently, I received the same notice.

> How should I proceed?

I think as it says "you don’t need to do anything".
Cheers.

**Comment by Chip000** [comment]
I thought it was strange google send it.
Thanks for the answer.

**Comment by Chip000** [comment]
Just to inform that nothing has happened until now.
Again thanks for your answer @vyachkonovalov

**Comment by JohnTheCoolingFan** [comment]
And today gmail module stopped showing unread messages count...
On my polybar:
![image](https://user-images.githubusercontent.com/43478602/62736430-ffd9af00-ba35-11e9-9bc3-550bddf83fa6.png)
When I launch by hand:
```
%{F#e06c75} %{F-}revoked/expired credentials
```
And when I try to re-auth:
```
Traceback (most recent call last):
  File "./auth.py", line 18, in <module>
    credentials.refresh(httplib2.Http())
  File "/usr/lib/python3.7/site-packages/oauth2client/client.py", line 545, in refresh
    self._refresh(http)
  File "/usr/lib/python3.7/site-packages/oauth2client/client.py", line 761, in _refresh
    self._do_refresh_request(http)
  File "/usr/lib/python3.7/site-packages/oauth2client/client.py", line 819, in _do_refresh_request
    raise HttpAccessTokenRefreshError(error_msg, status=resp.status)
oauth2client.client.HttpAccessTokenRefreshError: invalid_grant: Token has been expired or revoked.
```

**Comment by Chip000** [comment]
> And today gmail module stopped showing unread messages count...
> On my polybar:
> ![image](https://user-images.githubusercontent.com/43478602/62736430-ffd9af00-ba35-11e9-9bc3-550bddf83fa6.png)
> When I launch by hand:
> 
> ```
> %{F#e06c75} %{F-}revoked/expired credentials
> ```
> 
> And when I try to re-auth:
> 
> ```
> Traceback (most recent call last):
>   File "./auth.py", line 18, in <module>
>     credentials.refresh(httplib2.Http())
>   File "/usr/lib/python3.7/site-packages/oauth2client/client.py", line 545, in refresh
>     self._refresh(http)
>   File "/usr/lib/python3.7/site-packages/oauth2client/client.py", line 761, in _refresh
>     self._do_refresh_request(http)
>   File "/usr/lib/python3.7/site-packages/oauth2client/client.py", line 819, in _do_refresh_request
>     raise HttpAccessTokenRefreshError(error_msg, status=resp.status)
> oauth2client.client.HttpAccessTokenRefreshError: invalid_grant: Token has been expired or revoked.
> ```

remove credentials.json and rerun ~/.config/polybar/gmail/auth.py

**Comment by crabvk** [comment]
You're right. It's not so obvious but you should remove _credentials.json_ before running _auth.py_.  
  
Now to pass verification process for the app, google says that
* You must have a privacy policy URL.
* Add URLs for your homepage and Terms of Service if you have them.

I don't have privacy policy (don't even know what it is).
And don't have homepage either.
So, just for now, get new credentials and ignore the warning about **SUPER DANGER** app.
