### ISSUE TITLE
Select only Primary emails

### ISSUE THREAD

**Issue by adriencarbonaro** [vyachkonovalov/polybar-gmail#7]
Hello,

I've started using your module in Polybar and it works great.
The only thing is that it tells me that I have **5525 emails** which is true if I count the "Social" and "Promotions" emails that I never look into.

Would there be an option in Gmail API to select only the **Primary** content so it tells me I have 4 unread instead of 5524 ?

Thank you.

EDIT : I've looked into [Gmail API](https://developers.google.com/gmail/api/guides/labels) and found that you can use **Labels** to search you're emails, including `CATEGORY_PERSONAL` which is the category I would like to search. I think that is a good start to what I'm looking for. I will look into the code tomorrow to try it.

**Comment by crabvk** [comment]
Hello.
Please check updated version (new --label argument).

**Comment by adriencarbonaro** [comment]
Great ! Thanks
