### ISSUE TITLE
Authentication Disabled Temporarily for this Application

### ISSUE THREAD

**Issue by needo37** [vyachkonovalov/polybar-gmail#8]
Upon executing auth.py I am greeted with the message:

Authentication Disabled Temporarily for this Application in my web browser.

**Comment by crabvk** [comment]
Sorry for the problem. The app is using Gmail API with OAuth consent screen, and that need verification which I didn't finished yet. I'll try to do it soon.

**Comment by erdemoney** [comment]
I am having the same issue. Is there an alternative way to log in or is the project just unusable right now...?

**Comment by crabvk** [comment]
@erdemoney
for new users I'm afraid it's unusable now

**Comment by erdemoney** [comment]
Thats too bad. You should probably put a disclaimer in the readme until its fixed.

**Comment by crabvk** [comment]
Just now I submitted the app for verification with already verified domain, so in a day or two authentication should work again.

**Comment by crabvk** [comment]
@needo37 @erdemoney
Should work now. Please get new version and try run `auth.py` again.

**Comment by erdemoney** [comment]
Thanks for the quick fix. It works great!

**Comment by vyachkonovalov** [comment]
19f52e115821c415c18c4f6f433e0358b7edaae5
284fb40dbe7468ef29a188f87a560f99eb4bd566
